[package]
name = "abci_app"
version = "0.1.0"
edition = "2021"

[dependencies]
# tendermint = "0.23.9"
tendermint-abci = "0.23.9"
tendermint-proto = "0.23.9"
protocols = {path = "../protocols"}
tonic = "0.7"