FROM debian:bullseye

RUN apt-get update && apt-get -y install libssl-dev && rm -rf /var/lib/apt/lists/*

#Binaries
COPY ./src/target/release/server /target/release/ 
COPY ./src/target/release/proxy_server /target/release/ 
COPY ./src/target/release/confgen /target/release/ 
COPY ./src/target/release/client_app /target/release/ 
COPY ./src/target/release/trusted_dealer /target/release/ 

#Config files (TODO: to remove eventually)
COPY ./src/network/src/config/tendermint_net/config.toml ./target/network/src/config/tendermint_net/
WORKDIR /target/release/

#after docker run you can override CMD 

CMD ["./server", "--", " --config-file conf/server_0.json", " --key-file conf/keys_0.json"] 