version: '3'

services:
  thetacrypt1:
    container_name: thetacrypt1
    build: 
      context: ..
      network: host
      dockerfile: ./demo/Dockerfile
    command: /target/release/proxy_server --config-file conf/server_0.json --key-file conf/keys_0.json
    env_file:
      - config.env
    volumes:
      - ./config:/target/release/conf:Z
    image: rust-threshold-library
    ports:
      - "27001:27000"
      - "50051:50050"
    restart: always
    networks:
      localnet:
        ipv4_address: 192.167.20.2

  thetacrypt2:
    container_name: thetacrypt2
    build:
      context: ..
      network: host
      dockerfile: ./demo/Dockerfile
    env_file:
      - config.env
    volumes:
      - ./config:/target/release/conf:Z      
    command: /target/release/proxy_server --config-file conf/server_1.json --key-file conf/keys_1.json
    image: rust-threshold-library
    ports:
      - "27002:27000"
      - "50052:50050"
    restart: always
    networks:
      localnet:
        ipv4_address: 192.167.20.3

  thetacrypt3:
    container_name: thetacrypt3
    build:
      context: ..
      network: host
      dockerfile: ./demo/Dockerfile
    env_file:
      - config.env
    volumes:
      - ./config:/target/release/conf:Z
    command: /target/release/proxy_server --config-file conf/server_2.json --key-file conf/keys_2.json
    image: rust-threshold-library
    ports:
      - "27003:27000"
      - "50053:50050"
    restart: always
    networks:
      localnet:
        ipv4_address: 192.167.20.4

  thetacrypt4:
    container_name: thetacrypt4
    build: 
      context: ..
      network: host
      dockerfile: ./demo/Dockerfile
    env_file:
      - config.env
    volumes:
      - ./config:/target/release/conf:Z
    command: /target/release/proxy_server --config-file conf/server_3.json --key-file conf/keys_3.json
    image: rust-threshold-library
    ports:
      - "27004:27000"
      - "50054:50050"
    restart: always
    networks:
      localnet:
        ipv4_address: 192.167.20.5

  abci1:
    container_name: abci1
    build: 
      context: ..
      network: host
      dockerfile: ./demo/abci.Dockerfile
    env_file:
      - config.env
    image: abci-img
    restart: always
    command: ./fair_order_app --listen-ip 192.167.20.6 --tcl-ip 192.167.20.2
    depends_on:
      - thetacrypt1
    networks:
      localnet:
        ipv4_address: 192.167.20.6

  abci2:
    container_name: abci2
    build: 
      context: ..
      network: host
      dockerfile: ./demo/abci.Dockerfile
    env_file:
      - config.env
    image: abci-img
    restart: always
    command: ./fair_order_app --listen-ip 192.167.20.7 --tcl-ip 192.167.20.3
    depends_on:
      - thetacrypt2
    networks:
      localnet:
        ipv4_address: 192.167.20.7

  abci3:
    container_name: abci3
    build: 
      context: ..
      network: host
      dockerfile: ./demo/abci.Dockerfile
    env_file:
      - config.env
    image: abci-img
    restart: always
    command: ./fair_order_app --listen-ip 192.167.20.8 --tcl-ip 192.167.20.4
    depends_on:
      - thetacrypt3
    networks:
      localnet:
        ipv4_address: 192.167.20.8

  abci4:
    container_name: abci4
    build: 
      context: ..
      network: host
      dockerfile: ./demo/abci.Dockerfile
    env_file:
      - config.env
    image: abci-img
    restart: always
    command: ./fair_order_app --listen-ip 192.167.20.9 --tcl-ip 192.167.20.5
    depends_on:
      - thetacrypt4
    networks:
      localnet:
        ipv4_address: 192.167.20.9

  tendermint1:
      container_name: tendermint1
      image: "tendermint/localnode:latest"
      ports:
        - "26656-26657:26656-26657"
        - "6060:6060"
        - "27000:26660"
        - "8080:8080"
      environment:
        - ID=0
        - LOG=${LOG:-tendermint.log}
      volumes:
        - ./tendermint:/tendermint:Z
      command: node --proxy_app=tcp://abci1:26658 --home ./node0
      depends_on:
        - abci1
      networks:
        localnet:
          ipv4_address: 192.167.20.10

  tendermint2:
    container_name: tendermint2
    image: "tendermint/localnode:latest"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./tendermint:/tendermint:Z
    command: node --proxy_app=tcp://abci2:26658 --home ./node1
    depends_on:
      - abci2
    networks:
      localnet:
        ipv4_address: 192.167.20.11

  tendermint3:
    container_name: tendermint3 
    image: "tendermint/localnode:latest"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./tendermint:/tendermint:Z
    ports:
      - "26661-26662:26656-26657"
    command: node --proxy_app=tcp://abci3:26658 --home ./node2
    depends_on: 
      - abci3
    networks:
      localnet:
        ipv4_address: 192.167.20.12

  tendermint4:
    container_name: tendermint4
    image: "tendermint/localnode:latest"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./tendermint:/tendermint:Z
    ports:
      - "26663-26664:26656-26657"
    command: node --proxy_app=tcp://abci4:26658 --home ./node3
    depends_on:
      - abci4
    networks:
      localnet:
        ipv4_address: 192.167.20.13

networks:
  localnet:
    driver: bridge
    name: threshold-net
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.20.0/16
