[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmos_crypto = {path = "../", version = "0.1.0"}
reqwest = "0.11.10" # reqwest with JSON parsing support
futures = "0.3.21" # for our async / await blocks
tokio = { version = "1.12.0", features = ["full"] } # for our async runtime
libp2p = "0.43.0"
async-std = { version = "1.11.0", features = ["attributes"] }
log = { version = "0.4.16" }
